# That form has some native params which is not the attributes

# For form its:
# action - action to handle form
# method - method like post or get
# attr - some attributes of form

# For fields its:
# type - there is type of the field
# label - it is label of field
# name - name attribute of field
# attr - some attributes of field

# For select type you should specify type: select and options, for example
#gender:
#  type: select
#    options:
#      - value: key
#      - valueAndValue

signup:
  attr:
    style:
      margin: auto
      width: 200px
  field:
    - email
    - name
    - gender:
        type: select
        options:
          one: hello
          two: second
    - lastName
    - password1
    - password2
    - submit:
        type: button

signupValue:
  email: molodyko13@gmail.com
  name: Ruslan
  lastName: Molodyko
  gender: two
  password1: 123456
  password2: 123456