# That form has some native params which is not the attributes

# For form its:
# action - action to handle form
# method - method like post or get
# attr - some attributes of form

# For fields its:
# type - there is type of the field
# label - it is label of field
# name - name attribute of field
# attr - some attributes of field

signup:
  action: /signup
  method: post
  attr:
    class: .my-form
    style:
      width: 250px
      margin: auto
  fields:
    email:
      label: email
      type: text
      name: email
    name:
      label: name
      type: text
      name: name
    lastName:
      label: last-name
      type: text
      name: lastName
#    gender:
#      type: select
#      options:
#        - male
#        - female
    password1:
      label: password
      type: password
      name: password1
    password2:
      label: password-repeat
      type: password
      name: password1
